version: '3.8'

services:
  database-app:
    build: .
    container_name: minimdb_app
    ports:
      - "8080:8080"
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    ipc: host
    stdin_open: true
    tty: true
    restart: unless-stopped
